const exec = require('child_process').exec;
const fs = require('fs');

exec('git rev-list --all --count', function(err, stdout) {
  const buildNumber = parseInt(stdout);
  const buildDate = new Date().getTime();
  const contents = `\
export default {
  BUILD_NUMBER: ${buildNumber},
  BUILD_DATE: new Date(${buildDate})
}
`;
  fs.writeFileSync('./src/js/version.autogenerated.js', contents);
});
