import VERSION from '../version.autogenerated';

export default class VersionInfo {
  static BUILD_NUMBER = VERSION.BUILD_NUMBER;
  static BUILD_DATE = VERSION.BUILD_DATE;

  static formatDate (date) {
    return `${date.getDate()}/${date.getMonth() + 1}/${date.getFullYear()}`;
  }

  constructor () {
    this.domElement = null;

    this.createDom();
  }

  createDom () {
    this.domElement = document.createElement('div');
    this.domElement.className = 'version-info';
    this.domElement.innerHTML = `
      <p class="version-info__item">
        v. ${VersionInfo.BUILD_NUMBER} (${VersionInfo.formatDate(VersionInfo.BUILD_DATE)})
      </p>
    `;
  }
}
